### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by paliuca** [projectivemotion/wizzair-scraper#1]
Any chance for a new update. wizzair change the api ? Thanks

**Comment by projectivemotion** [comment]
Hello. I will check update it in the next couple of days.

**Comment by artaxmax** [comment]
To make it work, enough change api version here: src/Scraper.php:106, from "3.6.0" to "3.7.0".

**Comment by projectivemotion** [comment]
Thanks @artaxmax ! I have fixed it and created a constant on line 15 of Scraper.php for future version changes! @paliuca
