### ISSUE TITLE
Current API version?

### ISSUE THREAD

**Issue by maximdyatel** [projectivemotion/wizzair-scraper#10]
Hi! Help please, 
8.7.1 doesn't work now. Tried another (8.7.2....8.8.1) - can't find.  thanks!

**Comment by vifreefly** [comment]
@maximdyatel  current api version is `9.0.0`.

@projectivemotion, hello! I'm not good at PHP, but do I understand correctly that the logic of the script is: first it is doing GET request to the main page (`https://wizzair.com`), collect received cookies, and then doing another POST request to an API url **with these cookies** and provided options (origin/destination airport, time, etc.).  

Looks like wizzair.com massively changed things on their website recently and added a lot of protection against scraping. Now the api version is `9` and API url is `https://be.wizzair.com/9.0.0/Api/search/search`. I tried to use cookies from normal http response (curl) or even from PhantomJS - no luck.

The ticket information even doesn't loading when use PhantomJS or Selenium (Chrome or Firefox). When browser using directly, all info loading correctly though. I found that they now sending requests with browser fingerprint to their API, to theck if client trustworthy or not. 

I spend on it almost the whole day, but didn't found a reasonable solution (I think something like Puppeteer should work though). Please let me know if you'll find the way to make the API scraping work again. Thanks.

**Comment by projectivemotion** [comment]
I did some quick tests with 9.0.0 api and you're right @vifreefly they seem to have changed the way they validate cookies. Interesting. I do not have a solution for this yet. Maybe someone else can help us solve this puzzle.

**Comment by boryzo** [comment]
Ohhh, so sad. I though that I'll save time using your script. Ryanair scrapping is easy as hell, no cookies, only url and you got json as a result.

**Comment by bobod** [comment]
I have exactly the same problem. Have you found any solution?

**Comment by micovi** [comment]
@vifreefly have you found a solution yet or tried any fixes? I am currently in the same situation right now and I am still researching for ideas to bypass their new security.

**Comment by vifreefly** [comment]
@micovi  Yes. You have to use something like Puppeteer https://github.com/GoogleChrome/puppeteer , and hide the fact that it is an automated browser (follow this guide https://intoli.com/blog/not-possible-to-block-chrome-headless/). Then, using Chrome, you need go to the Wizzair homepage and copy all cookies.

Using these cookies, you can make any requests to their API.

**Comment by justaskz** [comment]
@vifreefly I found that cookies expire very fast. If you fast enough, it is possible to make ordinary request. So copying cookies from Chrome does not look as feasible solution. 

However I am not 100% sure if the problem is cookie expiration. How often do you need to re copy cookies?

**Comment by uacode** [comment]
> How often do you need to re copy cookies?
After five request, API block cookie

**Comment by evgeny-g** [comment]
azair.eu fixed this problem, so solution is exists. There is problem with akamai, it is tried to detect real user using JS into your browser, and it is sending fingerprint to akamai host.

**Comment by micovi** [comment]
I managed to make the requests with puppeteer by reaching the homepage first. After the homepage I made a interceptedRequest to add my POST data and loaded the api endpoint of search. Seems to work well.

**Comment by maximdyatel** [comment]
> I managed to make the requests with puppeteer. Seems to work well on my tests

Could you explain how you use puppeteer for making requests?
Thanks.

**Comment by alexeiTruhin** [comment]
If anyone is interested in the JS version, you could get inspired from my repo: https://github.com/alexeiTruhin/wizzpricehistory/blob/master/main/wizz-api.js

**Comment by kunicmarko20** [comment]
Ty @alexeiTruhin, you can get latest version from https://wizzair.com/static/metadata.json

**Comment by tssvitaly** [comment]
any ideas hot to adapt the json request with new {"apiUrl":"https://be.wizzair.com/9.17.0/Api"}

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Message>
The requested resource does not support http method 'GET'.
</Message>
</Error>

**Comment by kunicmarko20** [comment]
https://wizzair.com/static/metadata.json is gone, not sure if this is a new thing since version `10.0.0` (didn't use my app in a while), but you can use https://wizzair.com/buildnumber to get the correct url.

**Comment by kunicmarko20** [comment]
Just checked @alexeiTruhin repo and saw you can use `https://wizzair.com/static_fe/metadata.json` for metadatada, they added `_fe`?

**Comment by projectivemotion** [comment]
Hello everyone! Apparently this scraper is still functional. I have run the demo after upgrading the wizzair api to 10.3.0 and it showed me an array of results.

**Comment by tssvitaly** [comment]
> Hello everyone! Apparently this scraper is still functional. I have run the demo after upgrading the wizzair api to 10.3.0 and it showed me an array of results.

Could you please share your current version of the script.

**Comment by projectivemotion** [comment]
> > Hello everyone! Apparently this scraper is still functional. I have run the demo after upgrading the wizzair api to 10.3.0 and it showed me an array of results.
> 
> Could you please share your current version of the script.

I've updated the master branch with the latest version. Let me know if you get it working!
