### ISSUE TITLE
Hi again:)

### ISSUE THREAD

**Issue by paliuca** [projectivemotion/wizzair-scraper#2]
I can't make it work,
It always says : " Uncaught exception 'Exception' on \src\Scraper.php on line 111
What am I doing wrong ?
Thanks

**Comment by projectivemotion** [comment]
Hi @paliuca . Looks like the api version needed to be updated again. Newest api is 3.7.1. If you receive a 503 errror try updating the version manually in src/Scraper.php . I will add some code this week to try to bypass this version issue.

I have updated api version to 3.7.1 . 
please try cloning, running composer update, and then executing the demo/wizzair.php script . Let me know if you still have issues.

**Comment by nagytezsolt** [comment]
Hi, i think it has problem again with the api version. I got the same error as user paulica. What is the trick with the api version? Can i fix it on my side, or just you can? Thank You.

**Comment by paliuca** [comment]
Hi, yes I am still having the same problem. At first I thought is was the php version, but after changing to 5.6 same Exception. 
I did as you said, clone, composer update.
Thanks

**Comment by projectivemotion** [comment]
After looking at the problem, I found that for some dates wizzair responds with an empty result. 

For example:

```
/tmp/wizzair-scraper $ php -f demo/wizzair.php BFS VNO 2016-12-24 2016-12-27
Using Parameters: BFS - VNO / 2016-12-24 - 2016-12-27

An Error ocurred: The server returned a blank result.. You may want to try changing search parameters.

```

However changing the dates gives me a positive result:
```
/tmp/wizzair-scraper $ php -f demo/wizzair.php BFS VNO 2017-02-24 2017-02-27
Using Parameters: BFS - VNO / 2017-02-24 - 2017-02-27

..info..
```

I have updated the code to provide detailed error information. You can do git pull + composer update, or do a clean git clone & composer update, run the code and post here your specific error information.

**Comment by gabrbuiv** [comment]
Hi. I'm getting this error while trying to run on OSX:
`Gabrieliuss-MBP:wizzair-scraper gabrielius$ php -f demo/wizzair.php BFS VNO 2017-02-24 2017-02-27
Parse error: parse error in /Users/gabrielius/Desktop/wizzair-scraper-master/wizzair-scraper/demo/wizzair.php on line 32`

I don't have an experience with PHP, but I don't see anything suspicious on line 32. What could be wrong?

**Comment by projectivemotion** [comment]
Closing this issue. Please post a new issue if you are still having problems.
