### ISSUE TITLE
validationCodes

### ISSUE THREAD

**Issue by gabrbuiv** [projectivemotion/wizzair-scraper#3]
Hi. I've edited WizzAir API version in your code to 3.8.2. I'm getting this error while trying to run on OSX:

`}XXXX-MBP:demo XXXX$php -f wizzair.php BFS VNO 2016-03-21 2016-03-25
Using Parameters: BFS - VNO / 2016-03-21 - 2016-03-25

Warning: strtotime(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /Users/XXXX/Desktop/vendor/projectivemotion/wizzair-scraper/src/Scraper.php on line 57

Warning: strtotime(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /Users/XXXX/Desktop/vendor/projectivemotion/wizzair-scraper/src/Scraper.php on line 62

Warning: date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /Users/XXXX/Desktop/vendor/projectivemotion/wizzair-scraper/src/Scraper.php on line 67

Warning: date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /Users/XXXX/Desktop/vendor/projectivemotion/wizzair-scraper/src/Scraper.php on line 72
{
    "validationCodes": [
        "InvalidDepartureDate",
        "InvalidReturnDate"
    ]
}`

**Comment by gabrbuiv** [comment]
My bad. Wrong dates in the query.

**Comment by projectivemotion** [comment]
Glad you got it sorted out! There's a new version out today with automatic version detection.
