### ISSUE TITLE
Question - how to run this script?

### ISSUE THREAD

**Issue by nichalko** [projectivemotion/wizzair-scraper#8]
Hi,

So far I could not run this script...

tried: 
* `wizzair.php BFS VNO 2016-12-07 2016-12-09`
= opens the file.

* `php wizzair.php BFS VNO 2016-12-07 2016-12-09`
= 
```
Using Parameters: BFS - VNO / 2016-12-07 - 2016-12-09
Fatal error: Uncaught Error: Class 'projectivemotion\WizzairScraper\Scraper' not found in E:\wizz air scraper\wizzair-scraper\demo\wizzair.php:32
Stack trace:
#0 {main}
  thrown in E:\wizz air scraper\wizzair-scraper\demo\wizzair.php on line 32

```
I installed by cloning the repo but Composer did not update due to

```
 [Composer\Exception\NoSslException]
  The openssl extension is required for SSL/TLS protection but is not available. If you can not enable the openssl e
  xtension, you can disable this error, at your own risk, by setting the 'disable-tls' option to true.
```

**Comment by gladk** [comment]
I think this script is outdated now. wizzair has released many api versions since the last commit. Not sure it is possible to use this script now.

But your error looks like not related to this problem.

**Comment by projectivemotion** [comment]
You forgot to run `composer update` to download the dependencies. Closing.
